# Generated by Django 4.0.1 on 2022-01-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_kuller_operativka_processor_videocard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operativka',
            name='pamyat',
            field=models.CharField(max_length=200, verbose_name='Память, гб'),
        ),
    ]
