# Generated by Django 4.0.1 on 2022-01-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_delete_kuller_delete_processor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operativka',
            name='name',
            field=models.CharField(max_length=200, verbose_name='название оперативной памяти'),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='name',
            field=models.CharField(max_length=200, verbose_name='название видеокарты'),
        ),
    ]
